site:
  title: Documentation
  start_page: tutorials::index.adoc
  url: http:localhost:3000
  keys:
    docsearch_id: 'QK2EAH8GB0'
    docsearch_api: 'ef7bd9485eafbd75d6e8425949eda1f5'
    docsearch_index: 'prod_hazelcast_docs'
content:
  sources: 
  - url: https://github.com/hazelcast/hazelcast-docs
    branches: main
    start_paths: [tutorials, home]
  - url: https://github.com/hazelcast-guides/adoc-templates.git
    branches: antora-doc
  - url: https://github.com/JakeSCahill/caching-springboot-jcache
    branches: tutorials
    start_path: docs
  - url: https://github.com/JakeSCahill/hazelcast-embedded-springboot
    branches: tutorials
    start_path: docs
  - url: https://github.com/JakeSCahill/springboot-hibernate
    branches: tutorials
    start_path: docs
  - url: https://github.com/JakeSCahill/hibernate-jcache
    branches: tutorials
    start_path: docs
  - url: https://github.com/JakeSCahill/istio
    branches: tutorials
    start_path: docs
  - url: https://github.com/JakeSCahill/caching-micronaut
    branches: tutorials
    start_path: docs
  - url: https://github.com/JakeSCahill/kubernetes-embedded
    branches: tutorials
    start_path: docs
  - url: https://github.com/JakeSCahill/hazelcast-embedded-microprofile
    branches: tutorials
    start_path: docs
  - url: https://github.com/JakeSCahill/hazelcast-client-quarkus
    branches: tutorials
    start_path: docs
  - url: https://github.com/JakeSCahill/springboot-webfilter-session-replication
    branches: tutorials
    start_path: docs
  - url: https://github.com/JakeSCahill/caching-springboot
    branches: tutorials
    start_path: docs
  - url: https://github.com/JakeSCahill/ecs-embedded
    branches: tutorials
    start_path: docs
  - url: https://github.com/JakeSCahill/striim-cdc
    branches: tutorials
    start_path: docs
  - url: https://github.com/JakeSCahill/springboot-tomcat-session-replication
    branches: tutorials
    start_path: docs
  - url: https://github.com/JakeSCahill/vmware-tanzu
    branches: tutorials
    start_path: docs
  - url: https://github.com/JakeSCahill/terraform-quickstarts
    branches: tutorials
    start_path: docs
  - url: https://github.com/JakeSCahill/kubernetes-external-client
    branches: tutorials
    start_path: docs
  - url: https://github.com/JakeSCahill/active-directory-authentication
    branches: tutorials
    start_path: docs
  - url: https://github.com/JakeSCahill/kubernetes-sidecar
    branches: tutorials
    start_path: docs
  - url: https://github.com/JakeSCahill/kubernetes-hpa
    branches: tutorials
    start_path: docs
  - url: https://github.com/JakeSCahill/kubernetes-ssl
    branches: tutorials
    start_path: docs
  - url: https://github.com/JakeSCahill/kubernetes-wan
    branches: tutorials
    start_path: docs
  - url: https://github.com/JakeSCahill/kubernetes
    branches: tutorials
    start_path: docs
  - url: https://github.com/JakeSCahill/spring-session-hazelcast
    branches: tutorials
    start_path: docs
  - url: https://github.com/JakeSCahill/ec2-cluster
    branches: tutorials
    start_path: docs
  - url: https://github.com/JakeSCahill/linkerd
    branches: tutorials
    start_path: docs
  - url: https://github.com/JakeSCahill/consul
    branches: tutorials
    start_path: docs
  - url: https://github.com/JakeSCahill/openshift
    branches: tutorials
    start_path: docs
  - url: https://github.com/JakeSCahill/nodejs-client-getting-started
    branches: tutorials
    start_path: docs
  - url: https://github.com/JakeSCahill/go-client-getting-started
    branches: tutorials
    start_path: docs
  - url: https://github.com/JakeSCahill/openfaas-hz-client
    branches: tutorials
    start_path: docs
  - url: https://github.com/JakeSCahill/hazelcast-platform-operator-expose-externally
    branches: tutorials
    start_path: docs
ui: 
  bundle:
    url: https://github.com/hazelcast/hazelcast-docs-ui/releases/download/v2.16-BETA/ui-bundle.zip
    snapshot: true
asciidoc:
  attributes:
    page-pagination: true@
    # Allows us to use UI macros. See https://docs.asciidoctor.org/asciidoc/latest/macros/ui-macros/
    page-experimental: true
    idprefix: ''
    idseparator: '-'
  extensions:
    - ./lib/tabs-block.js